// src/react/ShutterClose.tsx
import React, { useRef, useEffect } from 'react'
import type { CSSProperties } from 'react'
import { useShutterClose } from './useShutterClose'
import type { ShutterCloseOptions } from '../core/types'

export interface ShutterCloseProps extends ShutterCloseOptions {
  children: React.ReactNode
  isShut?: boolean
  onClosed?: () => void
  onOpened?: () => void
  className?: string
  style?: CSSProperties
}

export function ShutterClose({
  children,
  isShut: isShutProp = false,
  onClosed,
  onOpened,
  className,
  style,
  ...opts
}: ShutterCloseProps): React.JSX.Element {
  const ref = useRef<HTMLDivElement>(null)
  const hookOpts = {
    ...opts,
    ...(onClosed !== undefined && { onClose: onClosed }),
    ...(onOpened !== undefined && { onOpen: onOpened }),
  }
  const { close, open } = useShutterClose(
    ref as React.RefObject<HTMLElement>,
    hookOpts,
  )

  const prevRef = useRef(isShutProp)
  useEffect(() => {
    if (isShutProp === prevRef.current) return
    prevRef.current = isShutProp
    if (isShutProp) void close()
    else void open()
  }, [isShutProp, close, open])

  return (
    <div
      ref={ref}
      className={className}
      style={{ position: 'relative', ...style }}
    >
      {children}
    </div>
  )
}

// src/vue/ShutterClose.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useShutterClose } from './useShutterClose'
import type { ShutterCloseOptions } from '../core/types'

interface Props extends ShutterCloseOptions {
  isShut?: boolean
  class?: string
}

const props = withDefaults(defineProps<Props>(), { isShut: false })

const emit = defineEmits<{
  closed: []
  opened: []
}>()

const el = ref<HTMLElement | null>(null)

const { close, open } = useShutterClose(el, () => ({
  slats: props.slats,
  duration: props.duration,
  heightMultiplier: props.heightMultiplier,
  deceleration: props.deceleration,
  easing: props.easing,
  sign: props.sign,
  onClose: () => emit('closed'),
  onOpen: () => emit('opened'),
}))

watch(
  () => props.isShut,
  async (val, old) => {
    if (val === old) return
    if (val) await close()
    else await open()
  },
)
</script>

<template>
  <div ref="el" :class="props.class" style="position: relative">
    <slot />
  </div>
</template>
